/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisb' at '14/11/16 13:55' with Gradle 3.1
 *
 * @author luisb, @date 14/11/16 13:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
